server:
  port: 9004

spring:
  application:
    name: CONTRACT-SERVICE
  datasource:
    username: root
    password: bc@135
    url: jdbc:mysql://54.160.183.45:30002/seeder
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: false
    encoding: UTF-8
    out-of-order: true
    url: jdbc:mysql://54.160.183.45:30002/seeder
    user: root
    password: bc@135

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/