
server:
  port: 9005

spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:classpath:.env[.properties]
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
      routes:
        - id: CASHKICK-SERVICE
          uri: lb://cashkick-service
          predicates:
            - Path=/api/cashkick/**,/api/cashkickContract/**
          filters:
            - AuthenticationFilter
        - id: CONTRACT-SERVICE
          uri: lb://contract-service
          predicates:
            - Path=/api/contract/**
          filters:
            - AuthenticationFilter
        - id: USER-SERVICE
          uri: lb://user-service
          predicates:
            - Path=/api/user/**,/api/userFunds/**
          filters:
            - AuthenticationFilter
        - id: PAYMENT-SERVICE
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
